spring:
  application:
    name: msclientes
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testeclientedb
    username: postgres
    password: 123
    jpa:
      hibernate:
        ddl-auto: create
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka



